import "./globals.css";
import type { Metadata } from "next";

//COMPONENTS
import Layout from "./components/Layout";

export const metadata: Metadata = {
  title: "Real-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
